#!/usr/bin/env bash
# ==============================================================================
# Interactive setup wizard for config.env — prompts for each value with a sensible
# default (press Enter to accept). Auto-detects a serverless warehouse and can
# suggest a catalog storage root. Writes config.env; then run: source config.env
#
# Usage: scripts/setup_config.sh
# ==============================================================================
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"; ROOT="$(cd "$HERE/.." && pwd)"
OUT="$ROOT/config.env"; EX="$ROOT/config.env.example"

[ -e /dev/tty ] || { echo "No terminal available. Copy config.env.example to config.env and edit it manually."; exit 1; }

# default value: existing config.env > config.env.example > builtin fallback
dflt() {
  local v=""
  [ -f "$OUT" ] && v=$(sed -nE "s/^export $1=\"?([^\"]*)\"?.*/\1/p" "$OUT" | tail -1)
  [ -z "$v" ] && [ -f "$EX" ] && v=$(sed -nE "s/^export $1=\"?([^\"]*)\"?.*/\1/p" "$EX" | tail -1)
  [ -z "$v" ] && v="$2"
  printf '%s' "$v"
}
ask() { # var default prompt  -> echoes chosen value
  local ans=""
  read -rp "  $3 [$2]: " ans </dev/tty || true
  printf '%s' "${ans:-$2}"
}

echo "== Sentiva RAG — config.env setup =="
echo "(press Enter to accept the [default])"
echo "Available CLI profiles:"; databricks auth profiles 2>/dev/null | sed 's/^/    /' || true

PROFILE=$(ask PROFILE "$(dflt PROFILE DEFAULT)" "Databricks CLI profile")
CATALOG=$(ask CATALOG "$(dflt CATALOG dbx_agent_lakebase)" "Unity Catalog catalog")
SCHEMA=$(ask SCHEMA "$(dflt SCHEMA rag)" "Schema")
LAKEBASE_PROJECT=$(ask LAKEBASE_PROJECT "$(dflt LAKEBASE_PROJECT sentiva-rag)" "Lakebase project base name")

# Auto-detect a serverless warehouse for the default
WH_DEF=$(dflt WAREHOUSE_ID "")
if [ -z "$WH_DEF" ]; then
  WH_DEF=$(databricks warehouses list --profile "$PROFILE" -o json 2>/dev/null | python3 -c "
import json,sys
try:
  d=json.load(sys.stdin); ws=d if isinstance(d,list) else d.get('warehouses',[])
  print(next((w['id'] for w in ws if w.get('enable_serverless_compute')), ''))
except: print('')" 2>/dev/null || echo "")
  [ -n "$WH_DEF" ] && echo "  (auto-detected serverless warehouse: $WH_DEF)"
fi
WAREHOUSE_ID=$(ask WAREHOUSE_ID "$WH_DEF" "Serverless SQL warehouse id")

LLM_ENDPOINT=$(ask LLM_ENDPOINT "$(dflt LLM_ENDPOINT databricks-gemini-3-5-flash)" "LLM endpoint")
EMBEDDING_ENDPOINT=$(ask EMBEDDING_ENDPOINT "$(dflt EMBEDDING_ENDPOINT databricks-qwen3-embedding-0-6b)" "Embedding endpoint")
APP_A_NAME=$(ask APP_A_NAME "$(dflt APP_A_NAME sentiva-agent-api)" "App A (agent API) name")
APP_B_NAME=$(ask APP_B_NAME "$(dflt APP_B_NAME sentiva-web)" "App B (web UI) name")
GATEWAY_SERVICE_ID=$(ask GATEWAY_SERVICE_ID "$(dflt GATEWAY_SERVICE_ID sentiva_llm)" "AI Gateway model-service id")
MLFLOW_EXPERIMENT=$(ask MLFLOW_EXPERIMENT "$(dflt MLFLOW_EXPERIMENT /Shared/sentiva-rag-traces)" "MLflow experiment path")
TRACE_TABLE_PREFIX=$(ask TRACE_TABLE_PREFIX "$(dflt TRACE_TABLE_PREFIX sentiva)" "OTel trace table prefix")
RETRIEVAL_K=$(ask RETRIEVAL_K "$(dflt RETRIEVAL_K 5)" "Retrieval top-K")

echo "Catalog storage root — enter an s3://.../abfss:// location, 'DEFAULT' (metastore default), or 'detect' to auto-suggest:"
CATALOG_STORAGE_ROOT=$(ask CATALOG_STORAGE_ROOT "$(dflt CATALOG_STORAGE_ROOT DEFAULT)" "CATALOG_STORAGE_ROOT")
if [ "$CATALOG_STORAGE_ROOT" = "detect" ]; then
  "$HERE/detect_storage_root.sh" "$PROFILE" "$CATALOG" || true
  CATALOG_STORAGE_ROOT=$(ask CATALOG_STORAGE_ROOT "DEFAULT" "CATALOG_STORAGE_ROOT (paste the recommended value above)")
fi

# preserve an existing auto-managed Lakebase project record, if any (managed by
# bootstrap.sh / teardown.sh — don't clobber an in-progress deployment's project)
ACTUAL_VAL=$(sed -nE 's/^export LAKEBASE_PROJECT_ACTUAL="?([^"]*)"?.*/\1/p' "$OUT" 2>/dev/null | tail -1)

cat > "$OUT" <<EOF
# Sentiva RAG per-environment config — generated by scripts/setup_config.sh.
# Re-run that script to change values, or edit here directly. Then: source config.env
export PROFILE="$PROFILE"
export CATALOG="$CATALOG"
export SCHEMA="$SCHEMA"
export LAKEBASE_PROJECT="$LAKEBASE_PROJECT"
export WAREHOUSE_ID="$WAREHOUSE_ID"
export LLM_ENDPOINT="$LLM_ENDPOINT"
export EMBEDDING_ENDPOINT="$EMBEDDING_ENDPOINT"
export APP_A_NAME="$APP_A_NAME"
export APP_B_NAME="$APP_B_NAME"
export GATEWAY_SERVICE_ID="$GATEWAY_SERVICE_ID"
export MLFLOW_EXPERIMENT="$MLFLOW_EXPERIMENT"
export TRACE_TABLE_PREFIX="$TRACE_TABLE_PREFIX"
export RETRIEVAL_K="$RETRIEVAL_K"
export CATALOG_STORAGE_ROOT="$CATALOG_STORAGE_ROOT"
EOF
[ -n "$ACTUAL_VAL" ] && printf '\n# Auto-managed by bootstrap.sh — actual (suffixed) Lakebase project. Removed by teardown.sh.\nexport LAKEBASE_PROJECT_ACTUAL="%s"\n' "$ACTUAL_VAL" >> "$OUT"

echo
echo "✓ Wrote $OUT"
echo "  Next:  source config.env   (then run scripts/preflight.sh)"
